call/core/urls.py
from django.urls import path

from call.core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('search/', views.search, name='search-user'),
]

call/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from call.core.api.viewsets import PersonViewSets

router = routers.DefaultRouter()
router.register(r'api/person', PersonViewSets, basename='person')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('call.core.urls', namespace='core')),
    path('', include(router.urls)),
]

call/core/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField('nome', max_length=500)

    def __str__(self):
        return self.name

call/core/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_POST

from call.core.models import Person


def index(request):
    context = {
        'persons': Person.objects.all().order_by('name')
    }
    return render(request, 'core/index.html', context)


@require_POST
def add(request):
    person = Person.objects.create(name=request.POST['name'])
    data = {
        'status': 200,
        'data': person.name
    }
    return JsonResponse(data)


def search(request):
    name = request.GET.get('name', False)
    context = dict(can_add=False, message='Pessoa já existe')
    if name:
        if not Person.objects.filter(name=name).exists():
            context['message'] = 'Pessoa não existe'
            context['can_add'] = True

    return JsonResponse(context)

call/core/templates/core/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<h1>Lista de Contatos</h1>
<form action="" method="post" id="form-cadastro">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Digite o nome" id="input">
  <p style="display: none" id="help"></p>
  <button>Cadastrar</button>
</form>
<ul id="list-persons">
  {% for person in persons %}
    <li>{{ person.name }}</li>
  {% empty %}
    <li>Você não tem contatos</li>
  {% endfor %}
</ul>
<script>
    {#const form = document.getElementById('form-cadastro')#}
    const input = document.getElementById('input')
    const p = document.getElementById('help')
    input.addEventListener('keyup', novo_ajax)


    function novo_ajax() {
        var myHeaders = new Headers();
        myHeaders.append("HTTP_X_REQUESTED_WITH", "XMLHttpRequest");
        fetch(`{% url 'core:search-user' %}?name=${input.value}`, {
            method: "GET",
            headers: myHeaders
        })
            .then(response => {
                response.json().then(result => {
                    console.log(result)
                    if (!result.can_add) {
                        p.innerText = result.message
                        p.setAttribute('style', 'color: red')
                    } else {
                        p.setAttribute('style', 'display: none')
                    }
                })
            })
            .catch(error => {
                console.log('deu erro', error)
            })
    }

    function ajax_raiz() {
        var xhr = new XMLHttpRequest();

        xhr.open('GET', `{% url 'core:search-user' %}?name=${input.value}`, true);
        xhr.send();
        xhr.onload = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                var result = JSON.parse(xhr.response)
                if (!result.can_add) {
                    p.innerText = result.message
                    p.setAttribute('style', 'color: red')
                } else {
                    p.setAttribute('style', 'display: none')
                }
            }
        }
    }

    {#form.addEventListener('submit', (event) => {#}
    {#    const data = new FormData(form)#}
    {#    event.preventDefault()#}
    {##}
    {#    const headers = {#}
    {#        method: "POST",#}
    {#        body: data,#}
    {#        headers: {#}
    {#            'csrfmiddlewaretoken': '{{ csrf_token }}'#}
    {#        }#}
    {#    }#}
    {##}
    {#    fetch('/api/person/', headers)#}
    {#        .then(response => {#}
    {#response.json().then(result => {#}
    {#const ul = document.getElementById('list-persons')#}
    {#const li = document.createElement("li")#}
    {#li.innerText = result.data#}
    {#ul.appendChild(li)#}
    {#            //})#}
    {#            console.log(response)#}
    {#        })#}
    {#        .catch(error => {#}
    {#            console.log('deu erro', error)#}
    {#        })#}
    {##}
    //)
</script>
</body>
</html>